# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-04-06 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interfaceData',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column=b'id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column=b'name', max_length=30)),
                ('describe', models.CharField(db_column=b'describe', max_length=50)),
                ('url', models.CharField(db_column=b'url', max_length=150)),
                ('method', models.CharField(db_column=b'method', max_length=10)),
                ('request_data', models.TextField(db_column=b'request_data', null=True)),
                ('except_desc', models.CharField(db_column=b'except_desc', max_length=20)),
                ('except_content', models.TextField(db_column=b'except_content')),
                ('add_time', models.DateTimeField(auto_now=True, db_column=b'add_time')),
                ('is_delete', models.BooleanField(db_column=b'is_delete', default=False)),
                ('delete_time', models.DateTimeField(db_column=b'delete_time', null=True)),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'interface_data',
            },
        ),
    ]
