# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-04-06 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacedata',
            name='url',
            field=models.TextField(db_column=b'url'),
        ),
    ]
